CREATE TABLE todos (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL
);

-- Insertar 100 registros de ejemplo
INSERT INTO todos (id, title, description) VALUES
('1', 'Completar documentación del proyecto', 'Revisar y actualizar toda la documentación técnica del proyecto'),
('2', 'Revisar código de seguridad', 'Auditar el código en busca de vulnerabilidades de seguridad'),
('3', 'Optimizar consultas de base de datos', 'Mejorar el rendimiento de las consultas SQL más lentas'),
('4', 'Implementar tests unitarios', 'Crear suite completa de tests unitarios para los módulos principales'),
('5', 'Actualizar dependencias', 'Revisar y actualizar todas las dependencias del proyecto'),
('6', 'Mejorar interfaz de usuario', 'Rediseñar la UI para mejor experiencia de usuario'),
('7', 'Configurar CI/CD pipeline', 'Implementar pipeline de integración y despliegue continuo'),
('8', 'Agregar logging estructurado', 'Implementar sistema de logging más robusto y estructurado'),
('9', 'Crear documentación de API', 'Generar documentación completa de los endpoints de la API'),
('10', 'Implementar caché Redis', 'Configurar Redis para mejorar el rendimiento de consultas frecuentes'),
('11', 'Agregar autenticación JWT', 'Implementar sistema de autenticación con tokens JWT'),
('12', 'Crear dashboard de monitoreo', 'Desarrollar dashboard para monitorear métricas del sistema'),
('13', 'Optimizar imágenes', 'Comprimir y optimizar todas las imágenes del proyecto'),
('14', 'Implementar paginación', 'Agregar paginación a las listas de resultados'),
('15', 'Crear sistema de notificaciones', 'Implementar sistema de notificaciones por email y push'),
('16', 'Agregar validación de formularios', 'Mejorar validación en frontend y backend'),
('17', 'Implementar búsqueda avanzada', 'Crear funcionalidad de búsqueda con filtros múltiples'),
('18', 'Configurar backup automático', 'Implementar sistema de backup automático de base de datos'),
('19', 'Agregar internacionalización', 'Implementar soporte multiidioma en la aplicación'),
('20', 'Crear sistema de reportes', 'Desarrollar módulo de generación de reportes'),
('21', 'Implementar rate limiting', 'Agregar límites de tasa para prevenir abuso'),
('22', 'Mejorar manejo de errores', 'Implementar manejo centralizado y consistente de errores'),
('23', 'Agregar métricas de performance', 'Implementar tracking de métricas de rendimiento'),
('24', 'Crear sistema de colas', 'Implementar sistema de colas para procesamiento asíncrono'),
('25', 'Optimizar bundle de frontend', 'Reducir tamaño del bundle JavaScript'),
('26', 'Implementar WebSockets', 'Agregar comunicación en tiempo real con WebSockets'),
('27', 'Crear sistema de permisos', 'Implementar sistema granular de permisos y roles'),
('28', 'Agregar tests de integración', 'Crear suite de tests de integración'),
('29', 'Implementar versionado de API', 'Agregar versionado para mantener compatibilidad'),
('30', 'Crear sistema de auditoría', 'Implementar logging de acciones importantes'),
('31', 'Optimizar queries N+1', 'Identificar y resolver problemas de queries N+1'),
('32', 'Agregar soporte para dark mode', 'Implementar tema oscuro en la interfaz'),
('33', 'Crear sistema de plantillas', 'Implementar sistema de plantillas reutilizables'),
('34', 'Implementar compresión gzip', 'Configurar compresión de respuestas HTTP'),
('35', 'Agregar sistema de comentarios', 'Implementar funcionalidad de comentarios'),
('36', 'Crear sistema de etiquetas', 'Implementar sistema de etiquetado y categorización'),
('37', 'Implementar exportación de datos', 'Agregar funcionalidad para exportar datos en varios formatos'),
('38', 'Agregar sistema de favoritos', 'Implementar funcionalidad de marcar como favorito'),
('39', 'Crear sistema de historial', 'Implementar registro de historial de cambios'),
('40', 'Optimizar carga de imágenes', 'Implementar lazy loading para imágenes'),
('41', 'Agregar sistema de compartir', 'Implementar funcionalidad de compartir contenido'),
('42', 'Crear sistema de plantillas de email', 'Desarrollar plantillas HTML para emails'),
('43', 'Implementar autocompletado', 'Agregar funcionalidad de autocompletado en búsquedas'),
('44', 'Agregar sistema de calificaciones', 'Implementar sistema de calificación y reseñas'),
('45', 'Crear sistema de suscripciones', 'Implementar gestión de suscripciones'),
('46', 'Implementar geolocalización', 'Agregar funcionalidad basada en ubicación'),
('47', 'Agregar sistema de recordatorios', 'Implementar sistema de recordatorios y notificaciones'),
('48', 'Crear sistema de plantillas de documentos', 'Desarrollar generador de documentos'),
('49', 'Implementar sincronización offline', 'Agregar capacidad de trabajar sin conexión'),
('50', 'Agregar sistema de versiones', 'Implementar control de versiones para documentos'),
('51', 'Crear sistema de colaboración', 'Implementar funcionalidad de trabajo colaborativo'),
('52', 'Implementar sistema de plantillas de respuestas', 'Crear respuestas rápidas predefinidas'),
('53', 'Agregar sistema de estadísticas', 'Implementar dashboard de estadísticas y analytics'),
('54', 'Crear sistema de plantillas de proyectos', 'Desarrollar plantillas para proyectos comunes'),
('55', 'Implementar sistema de archivos', 'Agregar gestión de archivos y documentos'),
('56', 'Agregar sistema de plantillas de tareas', 'Crear plantillas reutilizables para tareas'),
('57', 'Implementar sistema de seguimiento', 'Agregar tracking de progreso y estado'),
('58', 'Crear sistema de plantillas de formularios', 'Desarrollar constructor de formularios'),
('59', 'Implementar sistema de plantillas de reportes', 'Crear generador de reportes personalizados'),
('60', 'Agregar sistema de plantillas de emails', 'Desarrollar editor de plantillas de email'),
('61', 'Crear sistema de plantillas de notificaciones', 'Implementar plantillas para notificaciones'),
('62', 'Implementar sistema de plantillas de contratos', 'Desarrollar generador de contratos'),
('63', 'Agregar sistema de plantillas de facturas', 'Crear generador de facturas'),
('64', 'Implementar sistema de plantillas de presupuestos', 'Desarrollar generador de presupuestos'),
('65', 'Crear sistema de plantillas de cotizaciones', 'Implementar generador de cotizaciones'),
('66', 'Agregar sistema de plantillas de órdenes', 'Crear generador de órdenes de compra'),
('67', 'Implementar sistema de plantillas de recibos', 'Desarrollar generador de recibos'),
('68', 'Crear sistema de plantillas de certificados', 'Implementar generador de certificados'),
('69', 'Agregar sistema de plantillas de diplomas', 'Desarrollar generador de diplomas'),
('70', 'Implementar sistema de plantillas de invitaciones', 'Crear generador de invitaciones'),
('71', 'Crear sistema de plantillas de tarjetas', 'Implementar generador de tarjetas de presentación'),
('72', 'Agregar sistema de plantillas de volantes', 'Desarrollar generador de volantes'),
('73', 'Implementar sistema de plantillas de posters', 'Crear generador de posters'),
('74', 'Crear sistema de plantillas de banners', 'Implementar generador de banners'),
('75', 'Agregar sistema de plantillas de logos', 'Desarrollar generador de logos'),
('76', 'Implementar sistema de plantillas de iconos', 'Crear biblioteca de iconos'),
('77', 'Crear sistema de plantillas de gráficos', 'Implementar generador de gráficos'),
('78', 'Agregar sistema de plantillas de diagramas', 'Desarrollar generador de diagramas'),
('79', 'Implementar sistema de plantillas de mapas', 'Crear generador de mapas personalizados'),
('80', 'Crear sistema de plantillas de calendarios', 'Implementar generador de calendarios'),
('81', 'Agregar sistema de plantillas de horarios', 'Desarrollar generador de horarios'),
('82', 'Implementar sistema de plantillas de menús', 'Crear generador de menús'),
('83', 'Crear sistema de plantillas de listas', 'Implementar generador de listas'),
('84', 'Agregar sistema de plantillas de tablas', 'Desarrollar generador de tablas'),
('85', 'Implementar sistema de plantillas de formularios web', 'Crear constructor de formularios web'),
('86', 'Crear sistema de plantillas de páginas', 'Implementar generador de páginas'),
('87', 'Agregar sistema de plantillas de sitios', 'Desarrollar constructor de sitios web'),
('88', 'Implementar sistema de plantillas de blogs', 'Crear generador de blogs'),
('89', 'Crear sistema de plantillas de tiendas', 'Implementar constructor de tiendas online'),
('90', 'Agregar sistema de plantillas de portafolios', 'Desarrollar generador de portafolios'),
('91', 'Implementar sistema de plantillas de landing pages', 'Crear generador de landing pages'),
('92', 'Crear sistema de plantillas de dashboards', 'Implementar generador de dashboards'),
('93', 'Agregar sistema de plantillas de presentaciones', 'Desarrollar generador de presentaciones'),
('94', 'Implementar sistema de plantillas de documentos PDF', 'Crear generador de documentos PDF'),
('95', 'Crear sistema de plantillas de hojas de cálculo', 'Implementar generador de hojas de cálculo'),
('96', 'Agregar sistema de plantillas de bases de datos', 'Desarrollar constructor de bases de datos'),
('97', 'Implementar sistema de plantillas de APIs', 'Crear generador de APIs'),
('98', 'Crear sistema de plantillas de microservicios', 'Implementar generador de microservicios'),
('99', 'Agregar sistema de plantillas de contenedores', 'Desarrollar generador de configuraciones Docker'),
('100', 'Implementar sistema de plantillas de CI/CD', 'Crear generador de pipelines CI/CD');
